# Generated by Django 4.2.6 on 2023-11-15 18:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time at which an object was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time at which an object was modified",
                        verbose_name="updated_at",
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("body", models.TextField()),
                (
                    "image",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="url_image"
                    ),
                ),
                (
                    "is_draft",
                    models.BooleanField(default=True, verbose_name="is_draft"),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="published_date"
                    ),
                ),
                (
                    "url",
                    models.SlugField(
                        blank=True, max_length=255, null=True, verbose_name="url"
                    ),
                ),
            ],
            options={
                "ordering": ["-publish_date"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
    ]
